#spring:
# mvc:
#    view:
#      prefix: /WEB-INF/sixteam/
#      suffix: .jsp


spring:    
 datasource:
  url: jdbc:sqlserver://localhost:1433;databaseName=sixteamDB;trustServerCertificate=true
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  username: sixteam
  password: sixteam
  
 thymeleaf:
    cache: false
    prefix: classpath:/templates/     # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5

 jpa:
  database-platform: org.hibernate.dialect.SQLServerDialect 
  show-sql: true
  properties:
   hibernate:
    format-sql: true
    ddl-auto: update  
    naming:
     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    
     
  